# Generated by Django 4.0.4 on 2022-05-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descargas',
            name='lat',
            field=models.DecimalField(decimal_places=98, max_digits=100),
        ),
        migrations.AlterField(
            model_name='descargas',
            name='lng',
            field=models.DecimalField(decimal_places=98, max_digits=100),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='lat',
            field=models.DecimalField(decimal_places=98, max_digits=100),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='lng',
            field=models.DecimalField(decimal_places=98, max_digits=100),
        ),
    ]
