# Generated by Django 4.0.4 on 2022-05-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_descargas_lat_alter_descargas_lng_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descargas',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='descargas',
            old_name='lng',
            new_name='longitude',
        ),
    ]
